"""column-new-added

Revision ID: 2ebc3bd75440
Revises: afe2ab3a519c
Create Date: 2021-02-04 12:58:25.819898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebc3bd75440'
down_revision = 'afe2ab3a519c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'new')
    # ### end Alembic commands ###
