"""email_text column added

Revision ID: 71fad678f80c
Revises: afcd1703f1b4
Create Date: 2021-02-10 17:20:50.950564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fad678f80c'
down_revision = 'afcd1703f1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('email_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'email_text')
    # ### end Alembic commands ###
