"""confirmation table changed for column added to reservation

Revision ID: afcd1703f1b4
Revises: dbe410a58533
Create Date: 2021-02-07 12:34:22.678876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcd1703f1b4'
down_revision = 'dbe410a58533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    op.add_column('reservation', sa.Column('confirmation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'confirmation')
    op.create_table('confirmation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('confirmation', sa.TEXT(), nullable=True),
    sa.Column('res_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['res_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
